package com.team871.exception;

/**
 * The root of all Exceptions generated by US!
 */
public class RobotechException extends Exception {
    public RobotechException(String message) {
        super(message);
    }

    public RobotechException(String message, Throwable cause) {
        super(message, cause);
    }
}
